name: app
description: "Hanko Field"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.0
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.1.5
  firebase_messaging: ^15.2.1
  firebase_remote_config: ^5.3.0
  firebase_analytics: ^11.4.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.3
  logging: ^1.3.0
  url_launcher: ^6.3.2
  miniriverpod:
    path: ../../miniriverpod/miniriverpod

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0

flutter:
  uses-material-design: true
