name: app
description: "Hanko Field"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.0
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.1.5
  firebase_messaging: ^15.2.1
  firebase_remote_config: ^5.3.0
  firebase_analytics: ^11.4.3
  firebase_performance: ^0.10.1+5
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.1
  collection: ^1.18.0
  http: ^1.2.2
  logging: ^1.3.0
  url_launcher: ^6.3.2
  package_info_plus: ^8.1.2
  device_info_plus: ^10.1.2
  miniriverpod: ^0.0.2
  declarative_nav: ^0.0.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.5
  characters: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.0
  pdfx: ^2.6.0
  share_plus: ^10.1.2
  archive: ^3.6.1
  flutter_markdown: ^0.7.7
  flutter_widget_from_html: ^0.17.0
  webview_flutter: ^4.13.0
  file_picker: ^8.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

  integration_test:
    sdk: flutter
  network_image_mock: ^2.1.1

  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0

flutter:
  uses-material-design: true
