name: app
description: "Hanko Field"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_auth: ^5.5.0
  firebase_core: ^3.10.0
  firebase_crashlytics: ^4.1.5
  firebase_messaging: ^15.2.1
  firebase_remote_config: ^5.3.0
  firebase_analytics: ^11.4.3
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.1
  collection: ^1.18.0
  http: ^1.2.2
  logging: ^1.3.0
  url_launcher: ^6.3.2
  package_info_plus: ^8.1.2
  miniriverpod:
    path: ../../miniriverpod/miniriverpod
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  go_router: ^14.3.0
  google_sign_in: ^6.2.2
  sign_in_with_apple: ^6.1.3
  crypto: ^3.0.5
  characters: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  pdf: ^3.11.0
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  custom_lint: ^0.8.0

flutter:
  uses-material-design: true
